# Fichier netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

# Règle pour l'admin (laisse /admin tranquille)
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# Règle pour React (redirige tout le reste)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200